### ISSUE TITLE
Improving registration form for the 2020 Sprint Week 

### ISSUE THREAD

**Issue by EiffL** [LSSTDESC/meeting-registration-form#29]
I have created an initial draft of the sprint week registration form over here: http://lsstdesc.org/meeting-registration-form/
It's not functional yet, just for prototyping. 

I'm opening this issue to gather feedback on the form, please don't hesitate to comment below if you have any suggestions.
Our hope is to have the registration server setup and running by Nov. 6th 2020

**Comment by humnaawan** [comment]
thanks @EiffL! this is a great start. some comments:

- we had discussed adding a question re the level of tutorials that people might want to see. we had also considered providing a list of tutorials to choose from so that we have enough time to actually plan for them. what do you think?
- i think we can keep the session facilitator question (after an update so the content isn't about the July meeting)? im not sure if MAC would provide another tutorial though; i think we have the recording for the last tutorial.
- i think we can remove the bit about plenary recordings.

also, when we share the form with the Meetings Committee, we can ask if we want to re-introduce the question re pronouns.

**Comment by EiffL** [comment]
All comments sounds good to me!
And yeah I can add a section on tutorial topics. Maybe we will have specific tutorial by the time registration opens, if we dont, we can ask what area/topic people would like to be tutored on, to engage with given DESC activities

**Comment by humnaawan** [comment]
thanks so much for the updates! a few questions/comments:

1. can we add a few more tiers to the participation levels? e.g. "fully synchronous",  "fully asynchronous", "half/half"? also there's currently an option for "not sprinting" - should we have this option on the registration page? i guess im trying to think why would someone want to register if they dont want to sprint .. but perhaps they're there just for the tutorials or socializing?
2. is there a reason why "Do you have a working NERSC account?" is followed by an option re JupyterHub? There might be people who have an account on NERSC but dont know about JupyterHub - is the motivation of the question inquiry re NERSC account or access to NERSC-related things (i.e. JupyterHub, DESC kernels, etc)? another thing to perhaps consider is to add a link or short description of what NERSC is. i worry that super new members might not know what we are asking; if we dont want to add info, we could add something like "if you dont know what NERSC is, please check the second option"?
3. "Some of the plenary sessions " --? "Some of the tutorial sessions"?

thanks again!

**Comment by EiffL** [comment]
1. So the `not sprinting` was because some days people may not be able to attend. And yes, I can add a `partially synchronous` entry. I also thought of saying `mostly synchronous` or `mostly asynchronous`

2. Right.... I feel like what people need is access to JupyterLab. If they do, it means that they have a NERSC account, the  reverse is not necessarly true, they may have a nersc account but no idea how to access JupyterLab.
Good point about reference to NERSC.

3. Yep, changing that

**Comment by EiffL** [comment]
I have  made these changes, I have also added to the form a description of the different sprinting modes. Let me know what you think

**Comment by humnaawan** [comment]
things look great. a few more comments (sorry!):
- title: "Monday - **Thursday**, Nov. 30 - Dec. 4, 2020" --> "Monday - **Friday**, Nov. 30 - Dec. 4, 2020"
- session facilitators: "**The July 2020 meeting**" --> "**The virtual sprint week**"
- logistics:
    -- "several attendance modes are **proposed**:" --> "several attendance modes are **possible for you**:"?
    -- "can join impromptu discussions on **Zoom**." --> "can join impromptu discussions on **Zoom/Slack**."?
    -- "A mix of the above, " --> "A mix of the above**:**"?
    -- "you may expect " --> "you ~may~ expect "
    -- "To help accomodate participants from both sides of the Atlantic, two different sprint timeslots are proposed centered on Central European Standard Time, and East Standard Time" --> "To help **accommodate** participants from both sides of the Atlantic, we will have two ~different~ sprinting hubs: one centered on Central European Standard Time~,~ and **Pacific** Standard Time"
    -- perhaps add "Please see the event confluence page for a detailed schedule for the week" with a link to the main meeting page?

please lmk if you prefer that i incorporate these and issue a PR; i'm happy to do that.

**Comment by humnaawan** [comment]
thanks @EiffL for taking care of all the previous comments. based on our meeting today, can you please add:
- an inquiry re whether there are certain tutorials that people would like to see, with a link to the Stack Club tutorials and perhaps a mention of DESC-specific topics, e.g, DC2, 3x2pt, etc (i can currently only think of these as being more widely of interest). here's a draft suggestion for a (not-required) question:

> Are there specific topics on which you would like to see live tutorials? The topics could include DESC-specific ones like DC2, CCL, 3x2pt, etc.; or you could browse through the [LSST Stack Club tutorials](https://stackclub.readthedocs.io/en/latest/notebooks.html) and request a demonstration of a tutorial that may be relevant for you.

- add a question re whether one needs a mentor for the sprint week.
- add a question re whether one would be willing to be a mentor for the week.

also, perhaps it'd be good to add a mention that people can propose sprints, with a link to the sprints confluence page?

i'll go through the meeting notes again tomorrow to make sure we aren't missing anything.

**Comment by humnaawan** [comment]
also we need to update the description of the facilitator role to point out that facilitators will only be needed for the sprint pitches/wrap-ups and tutorials.

**Comment by EiffL** [comment]
ok I've added a tutorial field. How about we add the links to add sprints on the success message people see once they have registered?

**Comment by humnaawan** [comment]
that sounds like a great idea!

also we have received positive feedback re the mentor/mentee idea, with specific feedback to perhaps mention some examples of mentors to demonstrate that even junior members may be eligible to be mentors. here's an attempt:

> **Mentor/Mentee Sign-Up**
> We all know how difficult it can be to navigate a new space, with the potentially-daunting task of "sprinting" on research projects. The situation is even worse with a virtual event. To address this, the LOC will set up mentor/mentee pairs with the overarching goal of the effort to have a point of contact for attendees who might not know where to start. So:
> - If you are a new sprinter and/or would like some guidance on how to make the sprint week effective, would you like a mentor for the sprint week?
> [yes no]
> - If you know your way around DESC and/or have attended a sprint week, would you like to be a mentor for the sprint week? Note that the responsibilities for this role are not high; the main task for you would be to be available and open to fielding questions and directing your mentee to the right resources (people and/or documentation) etc. Note also that you do not have to be a senior member to be a mentor - junior members are especially encouraged to consider this opportunity!
> [yes no]

--

and finally, re a question re special accommodation: while it is unclear what kind of possible accommodations we can make, one suggestion is to add a question that doesn't necessarily promise anything but at least would allow us the opportunity to consider it for the next time, so here's an attempted draft:

> Do you require any special accommodation to make your participation most effective? Please note that we will try our best to accommodate your request but we may not be able to come through in time.


--
please modify as you see fit; i'm a bit rambly right now.

**Comment by EiffL** [comment]
Ok, thanks for this! I have implemented the changes. Let me know what you think.

**Comment by humnaawan** [comment]
thanks so much!

**Comment by EiffL** [comment]
Let's close it for now :-D then
