### ISSUE TITLE
Open links in different tabs to avoid interfering with registration process

### ISSUE THREAD

**Issue by EiffL** [LSSTDESC/meeting-registration-form#6]
At the moment, when a user clicks on an hyperlink the page is opened by default in the same window which can disrupt the registration process.

**Comment by yymao** [comment]
change all `target="_top"` to `target="_blank"`

**Comment by EiffL** [comment]
Thanks @yymao , I'm on it

**Comment by EiffL** [comment]
Thanks @yymao , that's some fast reviewing :-)
